version: "2.1"
services:
#  app:
#    # replace imageName with your image name (block in your case)
#    image: imageName:tag
#    ports:
#      - 9876:4000 # Replace the port of your application here if used
#    depends_on:
#      - db
  db:
    image: mongo
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"   